#### Content Based Filtering

In [1]:
import pandas as pd

movies_5000 = pd.read_csv('./datasets/tmdb_5000_movies.csv')
movies_5000.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [9]:
movies_5000['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [2]:
import ast
def value_import(x):
    return [i['name'] for i in ast.literal_eval(x)]
    
movies_5000['genres'] = movies_5000['genres'].apply(value_import)
movies_5000['keywords'] = movies_5000['keywords'].apply(value_import)

In [11]:
import ast
ast.literal_eval(movies['genres'][0])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [5]:
movies_5000['genres'][0]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [12]:
movies_5000.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[Action, Adventure, Science Fiction]",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
movies_5000['soup']=movies_5000['genres'] + movies_5000['keywords']

In [7]:
movies_5000['soup'][0]

['Action',
 'Adventure',
 'Fantasy',
 'Science Fiction',
 'culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [8]:
def join_words(x):
    return (' ').join(x)

movies_5000['soup_literal'] = movies_5000['soup'].apply(join_words)

In [9]:
movies_5000['soup_literal'][0]

'Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d'

In [11]:
movies_5000['soup_literal'].shape

(4803,)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer

count_vector = CountVectorizer()
soup_mat = count_vector.fit_transform(movies_5000['soup_literal'])

In [97]:
soup_mat

<4803x7164 sparse matrix of type '<class 'numpy.int64'>'
	with 63598 stored elements in Compressed Sparse Row format>

In [15]:
soup_mat.shape

(4803, 7164)

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

soup_similarity = cosine_similarity(soup_mat,soup_mat)

In [20]:
soup_similarity[2]

array([0.06537205, 0.08908708, 1.        , ..., 0.        , 0.        ,
       0.        ])

In [22]:
# 유사도가 큰것부터 영화ID를 내림차순 정리
soup_sim_sorted_ind = soup_similarity.argsort()[: , ::-1]
soup_sim_sorted_ind[0]

array([   0,  278,  541, ..., 2833, 2830, 2401], dtype=int64)

In [23]:
soup_sim_sorted_ind[1]

array([   1,   12,  199, ..., 2847, 2845, 2401], dtype=int64)

In [24]:
soup_sim_sorted_ind[1][1:11]

array([  12,  199,  340,   71, 2836,   17,  115,   30, 2875, 2655],
      dtype=int64)

In [26]:
movies_5000['original_title'][1]

"Pirates of the Caribbean: At World's End"

In [29]:
movies_5000['original_title'][soup_sim_sorted_ind[1][1:11]]

12             Pirates of the Caribbean: Dead Man's Chest
199     Pirates of the Caribbean: The Curse of the Bla...
340                                      Cutthroat Island
71                  The Mummy: Tomb of the Dragon Emperor
2836                                                Frida
17            Pirates of the Caribbean: On Stranger Tides
115                                               Hancock
30                                           Spider-Man 2
2875                                           Two Lovers
2655          Dungeons & Dragons: Wrath of the Dragon God
Name: original_title, dtype: object

In [30]:
# NearestNeighbors 를 활용한 유사도 
from sklearn.neighbors import NearestNeighbors

model_knn = NearestNeighbors(n_neighbors=20, metric='cosine')
model_knn.fit(soup_mat)

NearestNeighbors(metric='cosine', n_neighbors=20)

In [32]:
similarity ,  indices_result = model_knn.kneighbors(soup_mat[1] , n_neighbors=11)

In [35]:
indices_result[0][1:]

array([  12,  199,  340,   71, 2836,   17,   30,  115,    5, 2655],
      dtype=int64)

In [36]:
movies_5000['original_title'][indices_result[0][1:]]

12             Pirates of the Caribbean: Dead Man's Chest
199     Pirates of the Caribbean: The Curse of the Bla...
340                                      Cutthroat Island
71                  The Mummy: Tomb of the Dragon Emperor
2836                                                Frida
17            Pirates of the Caribbean: On Stranger Tides
30                                           Spider-Man 2
115                                               Hancock
5                                            Spider-Man 3
2655          Dungeons & Dragons: Wrath of the Dragon God
Name: original_title, dtype: object

In [38]:
# index : 영화제목 , value : 영화 index Series 
import pandas as pd

indices = pd.Series(movies_5000.index , index= movies_5000['original_title'])

indices

original_title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [39]:
indices['John Carter']

4

In [44]:
# 영화 제목을 입력하면 유사한 영화를 내림차순 정렬
idx = indices['John Carter']
result = list(enumerate(soup_similarity[idx]))
sorted_result = sorted(result , key=lambda x: x[1] , reverse=True)
sorted_result[1:21]

[(1326, 0.422890031611031),
 (260, 0.4168275107825463),
 (373, 0.3977961264790775),
 (972, 0.37953605763829484),
 (0, 0.3750457847507963),
 (3405, 0.3741657386773941),
 (754, 0.3718678720805473),
 (3494, 0.3703280399090205),
 (939, 0.36464644927248774),
 (278, 0.3643060444313497),
 (141, 0.3603749850782235),
 (1068, 0.35919055825961954),
 (47, 0.35856858280031806),
 (91, 0.35856858280031806),
 (1201, 0.3578300267477954),
 (541, 0.35675303400633784),
 (111, 0.3491486243775878),
 (2327, 0.34914862437758776),
 (1272, 0.3450327796711771),
 (400, 0.33806170189140666)]

In [45]:
import pandas as pd
def get_recommander(title , cosine_sim = soup_sim_sorted_ind , limit_idx=20):
    indices = pd.Series(movies_5000.index , index= movies_5000['original_title'])
    idx = indices[title]
    movie_indices = cosine_sim[idx][1:limit_idx+1]
    return movies_5000['original_title'].iloc[movie_indices]

In [51]:
title = input("당신이 좋아하는 영화를 입력하시오!!")
result = get_recommander(title=title , limit_idx=10)
print(result)

당신이 좋아하는 영화를 입력하시오!! Avatar

278          Planet of the Apes
541                     Soldier
838                      Alien³
4332             Silent Running
2403                     Aliens
47      Star Trek Into Darkness
373             Mission to Mars
3158                      Alien
1531                  Moonraker
2198                    Lockout
Name: original_title, dtype: object

In [52]:
# 가중평점이 좋은영화 유사한 영화 추천
C = movies_5000['vote_average'].mean()
# 투표횟수 중 60%이상의 횟수에 달하는 숫자
# 예를들어 총 투표횟수가 100과 1일때 m값은 매우 달라진다.
m = movies_5000['vote_count'].quantile(0.6)
def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    
    return ( (v/(v+m)) * R) + ( (m/(m+v)) * C)
    
movies_5000['weighted_vote'] = movies_5000.apply(weighted_vote_average, axis=1)

In [53]:
movies_5000.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,soup,soup_literal,weighted_vote
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[Action, Adventure, Fantasy, Science Fiction, ...",Action Adventure Fantasy Science Fiction cultu...,7.166301
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[Adventure, Fantasy, Action, ocean, drug abuse...",Adventure Fantasy Action ocean drug abuse exot...,6.838594
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,"[Action, Adventure, Crime, spy, based on novel...",Action Adventure Crime spy based on novel secr...,6.284091

In [57]:
import pandas as pd
def get_weighted_vote_recommander(title , cosine_sim = soup_sim_sorted_ind , limit_idx=20):
    indices = pd.Series(movies_5000.index , index= movies_5000['original_title'])
    idx = indices[title]
    movie_indices = cosine_sim[idx][1:limit_idx+1]
    return movies_5000.iloc[movie_indices].sort_values(by=['weighted_vote'] , ascending=False)['title']

In [59]:
get_weighted_vote_recommander(title='Avatar', limit_idx=10)

3158                      Alien
2403                     Aliens
47      Star Trek Into Darkness
838                      Alien³
4332             Silent Running
541                     Soldier
1531                  Moonraker
2198                    Lockout
373             Mission to Mars
278          Planet of the Apes
Name: title, dtype: object

In [60]:
title = input("당신이 좋아하는 영화를 입력하시오!!")
result = get_weighted_vote_recommander(title=title , limit_idx=10)
print(result)

당신이 좋아하는 영화를 입력하시오!! Avatar

3158                      Alien
2403                     Aliens
47      Star Trek Into Darkness
838                      Alien³
4332             Silent Running
541                     Soldier
1531                  Moonraker
2198                    Lockout
373             Mission to Mars
278          Planet of the Apes
Name: title, dtype: object

In [62]:
movies_5000.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'soup', 'soup_literal', 'weighted_vote'],
      dtype='object')

In [63]:
# soup 에 감독 과 출연진까지 반영
tmdb_df = pd.read_csv('./datasets/tmdb.csv')
tmdb_df.columns

Index(['Unnamed: 0', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'tittle', 'cast', 'crew', 'director',
       'soup'],
      dtype='object')

In [66]:
tmdb_df['director'][0]

'jamescameron'

In [73]:
tmdb_df['director'] = [[i] for i in tmdb_df['director']]

In [76]:
tmdb_df['cast'] = [[i] for i in tmdb_df['cast']]

In [71]:
movies_5000['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4803, dtype: object

In [78]:
movies_5000['soup_1'] = movies_5000['genres'] + movies_5000['keywords'] + tmdb_df['director'] + tmdb_df['cast']

In [81]:
def join_words(x):
    return (' ').join(x)
movies_5000['soup_1'][0]
# movies_5000['soup_1_literal'] = movies_5000['soup_1'].apply(join_words)

['Action',
 'Adventure',
 'Fantasy',
 'Science Fiction',
 'culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d',
 'jamescameron',
 "['samworthington', 'zoesaldana', 'sigourneyweaver']"]

#### User Based collaborative Filtering

In [82]:
import pandas as pd
import numpy as np

movies_df = pd.read_csv('./datasets/movies_small.csv')
ratings_df = pd.read_csv('./datasets/ratings_small.csv')

In [83]:
ratings_df.shape

(100836, 4)

In [84]:
movies_df.shape

(9742, 3)

In [85]:
ratings_df.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [86]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [87]:
# timestamp 제거
ratings_df.drop('timestamp' ,axis=1, inplace=True)

In [88]:
movie_ratings_df = pd.merge(movies_df, ratings_df, on="movieId")

In [89]:
movie_ratings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 5 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   movieId  100836 non-null  int64
 1   title    100836 non-null  object
 2   genres   100836 non-null  object
 3   userId   100836 non-null  int64
 4   rating   100836 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.8+ MB

In [90]:
movie_ratings_df.head()

,movieId,title,genres,userId,rating
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5

In [91]:
user_movie_rating_df = pd.pivot_table(movie_ratings_df, values='rating', index=['userId'],
                       columns=['title'])

In [93]:
user_movie_rating_df.iloc[0, :]

title
'71 (2014)                                   NaN
'Hellboy': The Seeds of Creation (2004)      NaN
'Round Midnight (1986)                       NaN
'Salem's Lot (2004)                          NaN
'Til There Was You (1997)                    NaN
                                            ...
eXistenZ (1999)                              NaN
xXx (2002)                                   NaN
xXx: State of the Union (2005)               NaN
¡Three Amigos! (1986)                        4.0
À nous la liberté (Freedom for Us) (1931)    NaN
Name: 1, Length: 9719, dtype: float64

In [94]:
user_movie_rating_df.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [95]:
# null을 0을 처리
user_movie_rating_df = user_movie_rating_df.fillna(0)

In [96]:
user_movie_rating_df.head()

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [100]:
#user 코사인 유사도 
user_cosine_sim = cosine_similarity(user_movie_rating_df , user_movie_rating_df)

In [109]:
list(enumerate(user_cosine_sim[0]))

[(0, 0.9999999999999998),
 (1, 0.027282865283323236),
 (2, 0.05972026184426369),
 (3, 0.19439476874364145),
 (4, 0.12907989044170284),
 (5, 0.1281515730334543),
 (6, 0.15874448829290932),
 (7, 0.13696806423879193),
 (8, 0.06426336406122543),
 (9, 0.01687529315758804),
 (10, 0.13249903811479113),
 (11, 0.01645753629196566),
 (12, 0.09297132615319638),
 (13, 0.11323836301879966),
 (14, 0.1606887994046495),
 (15, 0.16985840258785212),
 (16, 0.2643579462588918),
 (17, 0.21486847907467702),
 (18, 0.325376160305897),
 (19, 0.16096932024797223),
 (20, 0.15316181237861035),
 (21, 0.050690524586784254),
 (22, 0.10666932558956478),
 (23, 0.15519340508631405),
 (24, 0.09926135079189152),
 (25, 0.1057914869380478),
 (26, 0.2389329166582622),
 (27, 0.2030894442786486),
 (28, 0.1452507130731445),
 (29, 0.09978067036499101),
 (30, 0.16445415762154295),
 (31, 0.14621131861409523),
 (32, 0.15194516345275422),
 (33, 0.0835440483103031),
 (34, 0.07450797095509278),
 (35, 0.07167334576836212),
 (36, 0.14473624966363696),
 (37, 0.13858833948922747),
 (38, 0.3297822336575267),
 (39, 0.09475493436526691),
 (40, 0.10905268388090451),
 (41, 0.2556595612535332),
 (42, 0.12249834775940836),
 (43, 0.11082903614605927),
 (44, 0.3279216897772204),
 (45, 0.1099745160348043),
 (46, 0.06319281700767304),
 (47, 0.09807164003028777),
 (48, 0.1009294845656239),
 (49, 0.1060801596052782),
 (50, 0.12669869718423188),
 (51, 0.04878064444653664),
 (52, 0.06283953931023001),
 (53, 0.13063234688703718),
 (54, 0.06331379263897048),
 (55, 0.1341101769258153),
 (56, 0.3450342788075836),
 (57, 0.15753401855350263),
 (58, 0.20937352208625992),
 (59, 0.06656421811964176),
 (60, 0.11552236173432737),
 (61, 0.10821488883163072),
 (62, 0.2161586728178031),
 (63, 0.3152116613468185),
 (64, 0.06460406699801173),
 (65, 0.23352154672306585),
 (66, 0.1190460925882309),
 (67, 0.26540793511492267),
 (68, 0.15421278980709957),
 (69, 0.07806753093523121),
 (70, 0.09895547311055877),
 (71, 0.20996830357650256),
 (72, 0.0492170144823753),
 (73, 0.06306260972929494),
 (74, 0.14263912740593418),
 (75, 0.1829820297555039),
 (76, 0.0979550804981924),
 (77, 0.17798111220252888),
 (78, 0.21642622037554046),
 (79, 0.06530846438600083),
 (80, 0.10926093285298961),
 (81, 0.2160612306197488),
 (82, 0.11135558947952302),
 (83, 0.16540157542353215),
 (84, 0.016092274672569268),
 (85, 0.14739050626578518),
 (86, 0.032085951460214424),
 (87, 0.0714528967471258),
 (88, 0.025575590384158884),
 (89, 0.05184062285570966),
 (90, 0.3347269204181708),
 (91, 0.02876659526996001),
 (92, 0.23276622865499486),
 (93, 0.11008201670976782),
 (94, 0.17806854889765844),
 (95, 0.2827795137656078),
 (96, 0.08655715305137508),
 (97, 0.06218737985717063),
 (98, 0.06623056078986839),
 (99, 0.1477629896424435),
 (100, 0.14144681670674197),
 (101, 0.15646597899439538),
 (102, 0.2114796831625695),
 (103, 0.12117292709291355),
 (104, 0.09014197809328939),
 (105, 0.019424725713568243),
 (106, 0.06689432962138508),
 (107, 0.05790865979271026),
 (108, 0.15146455590757374),
 (109, 0.1429326162013055),
 (110, 0.07167358602883026),
 (111, 0.16729851943376065),
 (112, 0.072531676876461),
 (113, 0.07834230931128783),
 (114, 0.22525698385690535),
 (115, 0.18570774234344198),
 (116, 0.1651216259376412),
 (117, 0.1323331342564807),
 (118, 0.0572028228753115),
 (119, 0.11149054936897516),
 (120, 0.11780088436611574),
 (121, 0.19458886949380225),
 (122, 0.08560431242710081),
 (123, 0.19916896788619387),
 (124, 0.08968106261168893),
 (125, 0.13070509251714554),
 (126, 0.041907457734062556),
 (127, 0.15795040599452176),
 (128, 0.1869860974174465),
 (129, 0.08063001370493544),
 (130, 0.15102699535945727),
 (131, 0.16235262319155486),
 (132, 0.15771831274911244),
 (133, 0.14129771323649867),
 (134, 0.3239711545439711),
 (135, 0.11384733248485415),
 (136, 0.1893747917578224),
 (137, 0.028229662521852935),
 (138, 0.03360563546547189),
 (139, 0.200201566874236),
 (140, 0.1771556491055393),
 (141, 0.13816832265457513),
 (142, 0.027733195485391084),
 (143, 0.2045840686473293),
 (144, 0.0952391715936844),
 (145, 0.01710219109785255),
 (146, 0.088214534780675),
 (147, 0.01741450539029521),
 (148, 0.14473606603080008),
 (149, 0.08202043467158034),
 (150, 0.07865853063445094),
 (151, 0.12869192694652432),
 (152, 0.06684719845155426),
 (153, 0.03100475925484595),
 (154, 0.16131252940143836),
 (155, 0.20918863090126427),
 (156, 0.09097628828508374),
 (157, 0.037739159707221456),
 (158, 0.05829521070953401),
 (159, 0.2988826395811754),
 (160, 0.034997619412142134),
 (161, 0.0728712095344944),
 (162, 0.06426055859648619),
 (163, 0.21601487176556375),
 (164, 0.1391704482501213),
 (165, 0.25121443304513547),
 (166, 0.20487238778990088),
 (167, 0.10526900996640123),
 (168, 0.1587715828230285),
 (169, 0.09923734269103984),
 (170, 0.23003491959478053),
 (171, 0.14600181773351203),
 (172, 0.08970561462154047),
 (173, 0.12500690041419513),
 (174, 0.0),
 (175, 0.1380346558191348),
 (176, 0.20741367689269316),
 (177, 0.193449291603366),
 (178, 0.14210844713234821),
 (179, 0.16776228013105055),
 (180, 0.1139754430333454),
 (181, 0.26660031335153794),
 (182, 0.20412624008396862),
 (183, 0.005800554927516386),
 (184, 0.06029862299390886),
 (185, 0.24573695068267415),
 (186, 0.16002741039606275),
 (187, 0.05264842561944529),
 (188, 0.1049120961919249),
 (189, 0.027485751007356583),
 (190, 0.08095752171660987),
 (191, 0.10415470227278838),
 (192, 0.135522306745911),
 (193, 0.09903808184488094),
 (194, 0.22592644808053985),
 (195, 0.09567197466049888),
 (196, 0.13700379594269876),
 (197, 0.2694363429780011),
 (198, 0.2151480471655949),
 (199, 0.1889062501481353),
 (200, 0.24654062711781446),
 (201, 0.30938105715961617),
 (202, 0.09477682237876008),
 (203, 0.12603318914084716),
 (204, 0.05516367118182512),
 (205, 0.08896549704886964),
 (206, 0.11445834084210713),
 (207, 0.16940065628577078),
 (208, 0.11534372072274124),
 (209, 0.06387558633096846),
 (210, 0.1659842723242898),
 (211, 0.13050569855878313),
 (212, 0.0684112325774372),
 (213, 0.07177157234444655),
 (214, 0.2048139575955343),
 (215, 0.14313069039740206),
 (216, 0.3207129677163324),
 (217, 0.08864282244419508),
 (218, 0.2567358983753682),
 (219, 0.26989118663238515),
 (220, 0.1746258355667709),
 (221, 0.15612205710008648),
 (222, 0.15285439433584141),
 (223, 0.10484412773499947),
 (224, 0.15811207602358995),
 (225, 0.31092286320315454),
 (226, 0.08485654559836926),
 (227, 0.08988194167593269),
 (228, 0.11198235025616628),
 (229, 0.16796210020113495),
 (230, 0.16486849208308138),
 (231, 0.13997066195509586),
 (232, 0.15897561655418557),
 (233, 0.27720391807878664),
 (234, 0.11966738639353769),
 (235, 0.14330710148750592),
 (236, 0.08014242783001406),
 (237, 0.036593694407888185),
 (238, 0.29692183481374784),
 (239, 0.13501196176854177),
 (240, 0.0840426588674149),
 (241, 0.09809535501805394),
 (242, 0.042646975308125896),
 (243, 0.19696409445792856),
 (244, 0.005655439209412284),
 (245, 0.09444009119594313),
 (246, 0.2092352010857683),
 (247, 0.09244272805649188),
 (248, 0.18994932737101455),
 (249, 0.03674942601002984),
 (250, 0.1700534296054764),
 (251, 0.01781789000058343),
 (252, 0.012259517160813206),
 (253, 0.18926001778803003),
 (254, 0.087216146879352),
 (255, 0.05527217892997091),
 (256, 0.02915361378735415),
 (257, 0.08084480470953664),
 (258, 0.025066945086775254),
 (259, 0.12439396814848548),
 (260, 0.14916564983254857),
 (261, 0.06938330668590859),
 (262, 0.16298875270961935),
 (263, 0.13331520829108504),
 (264, 0.19304582164648484),
 (265, 0.3574077096032743),
 (266, 0.16353962174099015),
 (267, 0.15329189462946863),
 (268, 0.08346427907984902),
 (269, 0.10917734363594146),
 (270, 0.06831039963579222),
 (271, 0.053561431885334035),
 (272, 0.10561921292097858),
 (273, 0.2766318214469589),
 (274, 0.1876513229415331),
 (275, 0.14291722459120612),
 (276, 0.06441725368061882),
 (277, 0.06006303856543785),
 (278, 0.18647550129822313),
 (279, 0.0804864849011816),
 (280, 0.04600204863280287),
 (281, 0.24683595054045718),
 (282, 0.12785904708263462),
 (283, 0.12904745779085144),
 (284, 0.024876750524191426),
 (285, 0.16805257137795696),
 (286, 0.1751099888300366),
 (287, 0.32969952928292895),
 (288, 0.10870271170459045),
 (289, 0.19771415528355388),
 (290, 0.009776098394354385),
 (291, 0.21550029182096278),
 (292, 0.11999134296218554),
 (293, 0.2730443933901593),
 (294, 0.10912125721942867),
 (295, 0.11126097341660378),
 (296, 0.16805054937364422),
 (297, 0.20443598328434212),
 (298, 0.09673981709601198),
 (299, 0.0965741949582303),
 (300, 0.14853899638950693),
 (301, 0.13582598242675742),
 (302, 0.20172339242489962),
 (303, 0.24930142238085676),
 (304, 0.19703519595726363),
 (305, 0.0),
 (306, 0.2712569118295853),
 (307, 0.08958293681124767),
 (308, 0.09141503682803445),
 (309, 0.06853222732767901),
 (310, 0.06440497139196653),
 (311, 0.23671889744898345),
 (312, 0.35156151849095696),
 (313, 0.1464917376388459),
 (314, 0.011163158743848165),
 (315, 0.09285792465034327),
 (316, 0.16029612891574954),
 (317, 0.15314068948473655),
 (318, 0.058286391394723615),
 (319, 0.048134706013322634),
 (320, 0.10602618641793239),
 (321, 0.21269975920030035),
 (322, 0.14065570820702095),
 (323, 0.038350047142962945),
 (324, 0.13691004781104268),
 (325, 0.09170990544958889),
 (326, 0.09385483594479184),
 (327, 0.30226842833052076),
 (328, 0.04340587971441949),
 (329, 0.3221009263883462),
 (330, 0.060317489264420085),
 (331, 0.24770744842643258),
 (332, 0.024380224510970157),
 (333, 0.1552689058714764),
 (334, 0.16864250817210638),
 (335, 0.19316721205819606),
 (336, 0.10509651192624993),
 (337, 0.071704681843208),
 (338, 0.11609299750885238),
 (339, 0.12051112045015905),
 (340, 0.043658611820392004),
 (341, 0.08270179809853334),
 (342, 0.1415470469342827),
 (343, 0.16351974367414873),
 (344, 0.055672578233779704),
 (345, 0.10256910202525006),
 (346, 0.11506568177971882),
 (347, 0.14769885437046115),
 (348, 0.0988405036438845),
 (349, 0.09916974132065019),
 (350, 0.05079497598142549),
 (351, 0.15569922947172574),
 (352, 0.14175613057014014),
 (353, 0.28452295587501164),
 (354, 0.10410834177094395),
 (355, 0.2339637809450087),
 (356, 0.22594861653563691),
 (357, 0.0013000627990188993),
 (358, 0.15208963484470653),
 (359, 0.05631629552032759),
 (360, 0.09880443585120975),
 (361, 0.19399232174162723),
 (362, 0.10732111829737519),
 (363, 0.09989336410764503),
 (364, 0.06376789808448789),
 (365, 0.06758820418741977),
 (366, 0.1515617927902716),
 (367, 0.34512705158353046),
 (368, 0.17354289159259095),
 (369, 0.21259360969196858),
 (370, 0.11324646189641827),
 (371, 0.2545336260703227),
 (372, 0.14822254729021903),
 (373, 0.12179982601776777),
 (374, 0.08050060944074532),
 (375, 0.20106701981197317),
 (376, 0.058999315408180146),
 (377, 0.06253737459550866),
 (378, 0.13347156403322585),
 (379, 0.26443682112414557),
 (380, 0.22951248964591858),
 (381, 0.1366235464072591),
 (382, 0.00972001167926201),
 (383, 0.11650283619548685),
 (384, 0.265715284152712),
 (385, 0.14436374851988196),
 (386, 0.25755889525215836),
 (387, 0.014400187917918387),
 (388, 0.0748756230657413),
 (389, 0.09356047519542228),
 (390, 0.28320795795495024),
 (391, 0.10351468626600181),
 (392, 0.10016423743753274),
 (393, 0.14922697226747378),
 (394, 0.1301674309765989),
 (395, 0.09630927583499165),
 (396, 0.0),
 (397, 0.06787935493888976),
 (398, 0.20188423823893206),
 (399, 0.1953419900816621),
 (400, 0.034837963625872846),
 (401, 0.08496376339543071),
 (402, 0.17617229732654135),
 (403, 0.12396030141034312),
 (404, 0.12835377198829398),
 (405, 0.0364179660854943),
 (406, 0.10591015381432006),
 (407, 0.09647547264639139),
 (408, 0.15340846115513432),
 (409, 0.11185614276116777),
 (410, 0.14941880754085402),
 (411, 0.11316258478451416),
 (412, 0.11961259676082055),
 (413, 0.2818448276395981),
 (414, 0.168328304576003),
 (415, 0.11855891539204433),
 (416, 0.12972012736915578),
 (417, 0.1334166357222847),
 (418, 0.16792006519419525),
 (419, 0.14306058983217534),
 (420, 0.06496732602602169),
 (421, 0.09016063212886066),
 (422, 0.11166947437965435),
 (423, 0.1502786994532531),
 (424, 0.27060551537778466),
 (425, 0.05636282518073476),
 (426, 0.05160050432640393),
 (427, 0.25690773775882775),
 (428, 0.0458517925472045),
 (429, 0.08155043415119334),
 (430, 0.10138441949817088),
 (431, 0.13824858195007314),
 (432, 0.14214238266241497),
 (433, 0.2886089303809464),
 (434, 0.08331639640419372),
 (435, 0.09983640728415304),
 (436, 0.17378973309175721),
 (437, 0.1832833802800426),
 (438, 0.11955004579846659),
 (439, 0.021565888013732375),
 (440, 0.13988454077455958),
 (441, 0.037770270371847284),
 (442, 0.11709748062693252),
 (443, 0.13463669293259975),
 (444, 0.13569752355905415),
 (445, 0.14246723189517502),
 (446, 0.10256191262498504),
 (447, 0.25696210590166674),
 (448, 0.154714959731934),
 (449, 0.10029733469213872),
 (450, 0.11881240861256039),
 (451, 0.32804834442452885),
 (452, 0.2573643185063113),
 (453, 0.08228332652827243),
 (454, 0.12053994961860136),
 (455, 0.08315817731330775),
 (456, 0.1884201609113711),
 (457, 0.09436068654765879),
 (458, 0.03788322695531895),
 (459, 0.047454115065886315),
 (460, 0.08753950154295632),
 (461, 0.15274835642014678),
 (462, 0.10489245511361632),
 (463, 0.21304270388149305),
 (464, 0.21146266143815862),
 (465, 0.04193409059862059),
 (466, 0.05132276497004704),
 (467, 0.08473453494408474),
 (468, 0.330664315065201),
 (469, 0.15538026217000217),
 (470, 0.07364783908846007),
 (471, 0.03102666985045688),
 (472, 0.04577293532152272),
 (473, 0.21949441057034752),
 (474, 0.11137242314777995),
 (475, 0.09156269477924045),
 (476, 0.25549306655654075),
 (477, 0.052424929545784774),
 (478, 0.11940029940602953),
 (479, 0.32077506642773823),
 (480, 0.041028522167782855),
 (481, 0.11001410993973135),
 (482, 0.23596348103834253),
 (483, 0.17998333017485116),
 (484, 0.10402629022597486),
 (485, 0.1376990386495837),
 (486, 0.0616623542798114),
 (487, 0.09847642598623157),
 (488, 0.20857990812038155),
 (489, 0.08016585079341913),
 (490, 0.037487749830304985),
 (491, 0.07927192569034494),
 (492, 0.272494113636061),
 (493, 0.18626187469755032),
 (494, 0.10764663263555074),
 (495, 0.0),
 (496, 0.11383401409420564),
 (497, 0.14827582841478276),
 (498, 0.03636671942833231),
 (499, 0.16241461680930624),
 (500, 0.054132287929977735),
 (501, 0.1118888774055373),
 (502, 0.1306522964181605),
 (503, 0.03956774785046126),
 (504, 0.06523609012263713),
 (505, 0.0),
 (506, 0.11622950841012869),
 (507, 0.0944022632934357),
 (508, 0.12655531865331085),
 (509, 0.17457385915338816),
 (510, 0.06598355986253551),
 (511, 0.15341427553548526),
 (512, 0.1623711342614915),
 (513, 0.23319687309431034),
 (514, 0.0970376948300285),
 (515, 0.13880384424038103),
 (516, 0.18976944507360224),
 (517, 0.04333115368911226),
 (518, 0.029803375099915798),
 (519, 0.18578454629332383),
 (520, 0.08528844850680725),
 (521, 0.2093602039592056),
 (522, 0.04745673821640016),
 (523, 0.23737276414951464),
 (524, 0.200386152731779),
 (525, 0.08741412115007431),
 (526, 0.23924725350649603),
 (527, 0.13147769977122614),
 (528, 0.10422613578157405),
 (529, 0.10180297021586934),
 (530, 0.13335295024864086),
 (531, 0.22794347395922035),
 (532, 0.0816464773964779),
 (533, 0.15836476939670935),
 (534, 0.09935506551552939),
 (535, 0.10113019573215234),
 (536, 0.04263830034300707),
 (537, 0.03638922280486287),
 (538, 0.08164872214198644),
 (539, 0.14479218883604397),
 (540, 0.14041428203027653),
 (541, 0.142315370199075),
 (542, 0.06295011137620729),
 (543, 0.06077931278830563),
 (544, 0.04655176011730769),
 (545, 0.05383966246172576),
 (546, 0.030390285195086297),
 (547, 0.09272272714507301),
 (548, 0.127447812147475),
 (549, 0.03634195951548679),
 (550, 0.0980697688897096),
 (551, 0.19307355031116472),
 (552, 0.12386314620973615),
 (553, 0.14614207449587172),
 (554, 0.3028882906024456),
 (555, 0.0),
 (556, 0.14307255256291831),
 (557, 0.08351199299590066),
 (558, 0.1468069468849917),
 (559, 0.17368645900263915),
 (560, 0.3152540150361881),
 (561, 0.1809872980932968),
 (562, 0.031824776800013874),
 (563, 0.03474697635774071),
 (564, 0.12887746222101862),
 (565, 0.1447068956304059),
 (566, 0.05074132392104651),
 (567, 0.09909962944385972),
 (568, 0.10503332880141344),
 (569, 0.2825245266320322),
 (570, 0.09022444606230651),
 (571, 0.13107222676728095),
 (572, 0.25348044857429974),
 (573, 0.09345012697489036),
 (574, 0.0626677688096371),
 (575, 0.051802714511600706),
 (576, 0.3173191647230714),
 (577, 0.0),
 (578, 0.14112858224842978),
 (579, 0.2493255022248815),
 (580, 0.05739941071663011),
 (581, 0.04891399493902382),
 (582, 0.05217456100895368),
 (583, 0.10040602909255326),
 (584, 0.11407568035202417),
 (585, 0.12327969045449566),
 (586, 0.12278162583180302),
 (587, 0.18392155714925532),
 (588, 0.11811237155759456),
 (589, 0.3247662693123413),
 (590, 0.1368093873395915),
 (591, 0.14393382193216753),
 (592, 0.1744127536790812),
 (593, 0.14196021777008017),
 (594, 0.11055792628490169),
 (595, 0.12371278437882609),
 (596, 0.31284260192629904),
 (597, 0.01127997769239481),
 (598, 0.28241249505307064),
 (599, 0.2912719006345757),
 (600, 0.08055397165317552),
 (601, 0.16445467972635566),
 (602, 0.22148553316707534),
 (603, 0.0706685951517267),
 (604, 0.15362495574080526),
 (605, 0.1641914708159149),
 (606, 0.26938924011153337),
 (607, 0.2910973718143997),
 (608, 0.09357192999600525),
 (609, 0.14532080729594496)]

In [111]:
user_sim_sorted_ind = user_cosine_sim.argsort()[: , ::-1]
user_sim_sorted_ind[0][1:6]

array([265, 312, 367,  56,  90], dtype=int64)

In [113]:
# 타겟유저가 보지않은 영화를 비슷한 유저가 본영화중에 추천
# 타겟유저가 본영화 
taget_user = 0
target_user_rating_list = list(user_movie_rating_df.iloc[taget_user , : ])

In [118]:
target_user_movie = [x[0] for x in enumerate(target_user_rating_list) if x[1] !=0]

In [119]:
# 유사 유저가 본영화
other_user_movie = []
taget_user = 0
for i in user_sim_sorted_ind[taget_user][1:6]:
    result = [x[0] for x in enumerate(list(user_movie_rating_df.iloc[i , :])) if x[1] !=0 ]
    other_user_movie += result
list(set(other_user_movie))

[2048,
 2049,
 6,
 4106,
 2059,
 11,
 2061,
 6155,
 8206,
 4107,
 2064,
 4114,
 4113,
 2070,
 2072,
 2077,
 2079,
 6176,
 2083,
 4131,
 4134,
 2043,
 2086,
 4137,
 8234,
 4138,
 8231,
 2095,
 2099,
 60,
 63,
 6214,
 74,
 75,
 4173,
 6222,
 4176,
 2139,
 6236,
 2143,
 7753,
 8289,
 8290,
 2150,
 2151,
 8295,
 6247,
 7755,
 2158,
 2159,
 6255,
 6260,
 4222,
 8319,
 4231,
 136,
 6281,
 6282,
 8328,
 2188,
 6286,
 145,
 4241,
 8341,
 2197,
 2198,
 8344,
 6295,
 6297,
 2208,
 2212,
 2215,
 6311,
 8360,
 2218,
 8363,
 8361,
 2221,
 6317,
 8367,
 2224,
 2225,
 178,
 2226,
 4279,
 2233,
 8378,
 444,
 2237,
 2238,
 2240,
 2245,
 8391,
 4296,
 200,
 202,
 4300,
 6349,
 207,
 208,
 210,
 4309,
 216,
 2264,
 223,
 224,
 2274,
 2276,
 2277,
 2488,
 6377,
 234,
 4332,
 4334,
 4337,
 6389,
 245,
 2293,
 4344,
 4345,
 6394,
 6398,
 8448,
 2306,
 2308,
 261,
 2310,
 4367,
 2321,
 4369,
 6418,
 2327,
 282,
 285,
 290,
 291,
 292,
 296,
 8488,
 298,
 2348,
 4398,
 2350,
 6454,
 8509,
 4414,
 2369,
 4417,
 2372,
 325,
 327,
 329,
 332,
 333,
 334,
 8526,
 2380,
 4435,
 2388,
 4436,
 4438,
 4437,
 2387,
 2394,
 2395,
 2396,
 4445,
 9025,
 2401,
 4453,
 6501,
 2411,
 2413,
 6509,
 2415,
 2416,
 6511,
 2418,
 6513,
 370,
 6588,
 4476,
 6525,
 6529,
 4481,
 5776,
 390,
 4488,
 6539,
 2444,
 405,
 4501,
 2456,
 4509,
 4510,
 4511,
 2464,
 4512,
 6560,
 6564,
 4517,
 2471,
 427,
 2478,
 6578,
 435,
 4531,
 4532,
 6582,
 2487,
 4533,
 434,
 6580,
 6587,
 8636,
 2493,
 8638,
 6585,
 439,
 4545,
 4546,
 2499,
 8644,
 4549,
 2500,
 455,
 6595,
 4551,
 6598,
 8652,
 2511,
 6607,
 466,
 4562,
 470,
 8664,
 2521,
 473,
 8668,
 2528,
 8672,
 4576,
 6627,
 2531,
 8676,
 2536,
 6632,
 8683,
 494,
 6641,
 8690,
 6646,
 6648,
 6649,
 8700,
 4606,
 514,
 515,
 6661,
 2568,
 6667,
 2572,
 6668,
 6670,
 8719,
 8716,
 4624,
 8720,
 6675,
 8725,
 6681,
 4634,
 540,
 6691,
 8740,
 6693,
 8742,
 2599,
 6695,
 4645,
 4650,
 555,
 4655,
 2608,
 563,
 8756,
 8757,
 4662,
 565,
 8760,
 2616,
 4666,
 6715,
 6716,
 4669,
 6717,
 8767,
 2624,
 2619,
 579,
 6727,
 6728,
 8777,
 8779,
 6733,
 2638,
 4687,
 6735,
 591,
 8786,
 595,
 2641,
 4689,
 6740,
 6743,
 600,
 2648,
 601,
 6747,
 6744,
 2645,
 4702,
 4697,
 2656,
 6745,
 8793,
 4707,
 613,
 2663,
 6761,
 6762,
 4714,
 6769,
 2676,
 8820,
 631,
 6775,
 8825,
 2681,
 4737,
 2690,
 4738,
 8836,
 8838,
 6791,
 8843,
 2703,
 8850,
 4757,
 8853,
 6808,
 668,
 6812,
 4766,
 4767,
 8862,
 2718,
 674,
 675,
 4772,
 8869,
 4774,
 6823,
 8871,
 8872,
 6826,
 8875,
 6827,
 6829,
 8878,
 8879,
 2736,
 689,
 4785,
 8885,
 4790,
 697,
 2747,
 2749,
 8895,
 6848,
 706,
 2757,
 6856,
 2761,
 4808,
 715,
 8907,
 2766,
 8911,
 6865,
 2770,
 6868,
 2773,
 6871,
 6872,
 2779,
 2784,
 2785,
 2786,
 6883,
 2788,
 4838,
 744,
 8937,
 745,
 746,
 6889,
 749,
 753,
 8946,
 8947,
 755,
 8949,
 4854,
 8950,
 4856,
 761,
 2810,
 8954,
 8958,
 4867,
 6916,
 6915,
 6917,
 4871,
 6920,
 2826,
 2827,
 4876,
 2828,
 4882,
 2836,
 8980,
 8982,
 2838,
 4888,
 2842,
 6944,
 2848,
 8995,
 6948,
 805,
 806,
 9000,
 6955,
 812,
 4909,
 6960,
 6961,
 2867,
 9015,
 4919,
 6968,
 2874,
 827,
 9021,
 9022,
 831,
 9024,
 2880,
 2881,
 834,
 836,
 2885,
 6980,
 4933,
 840,
 839,
 2890,
 6982,
 6985,
 6989,
 6991,
 9039,
 2901,
 9045,
 6999,
 2905,
 861,
 4958,
 866,
 4964,
 2917,
 7018,
 4971,
 7019,
 2922,
 2923,
 4972,
 880,
 4978,
 9075,
 2931,
 9077,
 2934,
 887,
 7032,
 4985,
 2940,
 9084,
 7043,
 7044,
 2950,
 2951,
 904,
 7049,
 7050,
 909,
 9102,
 5005,
 7054,
 2961,
 7060,
 7065,
 7067,
 925,
 2974,
 9119,
 7069,
 7073,
 5029,
 5030,
 7079,
 5031,
 5032,
 9135,
 5041,
 946,
 2993,
 2997,
 9143,
 7096,
 3000,
 9144,
 5051,
 3007,
 3008,
 961,
 5058,
 3011,
 3013,
 966,
 965,
 5062,
 969,
 7113,
 9163,
 9164,
 3019,
 5074,
 5075,
 7125,
 7127,
 987,
 9180,
 9182,
 9183,
 992,
 5087,
 3043,
 997,
 3048,
 3051,
 7147,
 7149,
 3054,
 1007,
 1008,
 5103,
 1010,
 3059,
 1009,
 9205,
 3063,
 3065,
 7161,
 3067,
 7165,
 3069,
 1023,
 1025,
 9219,
 1028,
 7173,
 3078,
 5127,
 9224,
 7177,
 7178,
 3083,
 7180,
 3085,
 7184,
 7185,
 5138,
 5139,
 3092,
 5141,
 1046,
 7190,
 1048,
 7192,
 7193,
 3098,
 1052,
 5149,
 7196,
 9247,
 1056,
 9250,
 5155,
 9251,
 7205,
 1062,
 5157,
 3112,
 9252,
 3114,
 7211,
 5163,
 1069,
 1070,
 7213,
 7215,
 7216,
 1068,
 3117,
 7220,
 7217,
 7219,
 9270,
 1082,
 5181,
 1087,
 3135,
 7233,
 1089,
 5186,
 7236,
 7237,
 1091,
 3136,
 7240,
 7241,
 3138,
 3147,
 3148,
 3151,
 9297,
 5202,
 5203,
 5204,
 9298,
 3158,
 1106,
 5205,
 5206,
 1115,
 1116,
 7260,
 9307,
 1118,
 7259,
 7265,
 9308,
 5219,
 3172,
 7268,
 5224,
 1129,
 4685,
 3179,
 5229,
 7279,
 7283,
 3187,
 7287,
 1144,
 1145,
 1146,
 9339,
 3196,
 7293,
 7292,
 1151,
 7295,
 7299,
 3204,
 9349,
 1158,
 7303,
 9352,
 7305,
 9353,
 3215,
 7311,
 1167,
 7314,
 3216,
 7318,
 3226,
 9371,
 3229,
 7327,
 3237,
 9381,
 8785,
 3245,
 7341,
 3247,
 3248,
 3252,
 3254,
 3255,
 5304,
 3258,
 5306,
 7365,
 1223,
 7368,
 1226,
 1227,
 5324,
 5325,
 9422,
 1231,
 3279,
 3281,
 3282,
 9427,
 7377,
 1240,
 9433,
 1061,
 1244,
 3292,
 5340,
 7391,
 1247,
 1249,
 9442,
 1243,
 1253,
 5350,
 5351,
 5354,
 1262,
 7410,
 7412,
 1269,
 1270,
 3320,
 1272,
 5372,
 7421,
 1278,
 5374,
 3328,
 9471,
 1284,
 9477,
 7428,
 1287,
 9476,
 1290,
 9483,
 9484,
 9485,
 1292,
 3106,
 7439,
 1297,
 1298,
 5396,
 3350,
 7447,
 7446,
 7450,
 3356,
 5404,
 3357,
 7454,
 9502,
 1316,
 1322,
 5423,
 9525,
 1337,
 1338,
 5436,
 9534,
 1344,
 9537,
 1346,
 3395,
 1345,
 9542,
 9545,
 3402,
 3403,
 1356,
 3406,
 7503,
 5459,
 3413,
 1366,
 1367,
 3415,
 3418,
 1372,
 3420,
 5471,
 5474,
 7523,
 3428,
 3429,
 7528,
 5481,
 5482,
 1387,
 9581,
 5487,
 5488,
 7535,
 3441,
 1395,
 5491,
 3447,
 1403,
 5500,
 1410,
 7554,
 5510,
 5512,
 5514,
 1420,
 7565,
 9613,
 9615,
 3474,
 9621,
 7574,
 7577,
 1434,
 3485,
 5535,
 3489,
 9638,
 1447,
 7591,
 7593,
 1450,
 3499,
 3500,
 3501,
 3503,
 9647,
 3139,
 1459,
 3508,
 5555,
 3510,
 7210,
 9656,
 9657,
 9658,
 3515,
 5562,
 5564,
 5572,
 3526,
 3529,
 3530,
 7625,
 1482,
 5581,
 5582,
 5583,
 3539,
 5588,
 1496,
 1498,
 5595,
 9690,
 1501,
 1502,
 9697,
 3555,
 7653,
 3558,
 5607,
 3564,
 3570,
 9717,
 5623,
 7673,
 7680,
 3586,
 3589,
 5638,
 3590,
 1541,
 1545,
 1546,
 5641,
 5645,
 7694,
 7697,
 7698,
 5649,
 3603,
 3606,
 1560,
 3611,
 7711,
 1568,
 1569,
 5669,
 1574,
 7719,
 7718,
 5677,
 1584,
 7729,
 3634,
 7731,
 5680,
 7730,
 1593,
 3642,
 3643,
 5693,
 1598,
 5696,
 3649,
 1602,
 3655,
 3656,
 7752,
 5706,
 1611,
 5707,
 7757,
 3661,
 5711,
 3662,
 5709,
 7761,
 5715,
 7763,
 5720,
 1624,
 7770,
 7771,
 9279,
 1630,
 7777,
 3687,
 7787,
 1644,
 3696,
 7794,
 7799,
 7805,
 7811,
 5764,
 3717,
 7819,
 1676,
 1675,
 3728,
 7825,
 3729,
 1683,
 5780,
 3733,
 5782,
 5781,
 1684,
 1687,
 1689,
 5783,
 7837,
 1693,
 3742,
 5791,
 3754,
 1708,
 1713,
 3763,
 3766,
 3769,
 1724,
 7875,
 3782,
 1736,
 7881,
 7882,
 7887,
 ...]

In [133]:
import random
result_movie_index_list = list(set(list(set(other_user_movie))) - set(target_user_movie))

# 리스트에서 2개 랜덤 추출

random_movie_list = random.sample(result_movie_index_list, 10)

In [134]:
movies_series = pd.Series(movies_df['title'] , index=movies_df.index)
movies_series

0                                Toy Story (1995)
1                                  Jumanji (1995)
2                         Grumpier Old Men (1995)
3                        Waiting to Exhale (1995)
4              Father of the Bride Part II (1995)
                          ...
9737    Black Butler: Book of the Atlantic (2017)
9738                 No Game No Life: Zero (2017)
9739                                 Flint (2017)
9740          Bungo Stray Dogs: Dead Apple (2018)
9741          Andrew Dice Clay: Dice Rules (1991)
Name: title, Length: 9742, dtype: object

In [135]:
movies_series[random_movie_list]

5932    March of the Penguins (Marche de l'empereur, L...
2245                                 Guardian, The (1990)
8720                                American Heist (2015)
5304    Funny Thing Happened on the Way to the Forum, ...
2444                                Bodyguard, The (1992)
7994    Love Lasts Three Years (L'amour dure trois ans...
5889                                 San Francisco (1936)
4689                                   Hudson Hawk (1991)
3172                            Mummy Returns, The (2001)
6084                          Mozart and the Whale (2005)
Name: title, dtype: object